apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-storage
  namespace: apps
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
