apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analysis-storage
  namespace: apps
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
