apiVersion: v1
kind: Service
metadata:
  name: pgwas-mongo-service
  namespace: dbs
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    role: mongo-db-pgwas
