apiVersion: v1
kind: Service
metadata:
  name: pgwas-mongo-0-db-ext
  namespace: dbs
spec:
  type: NodePort
  selector:
    mongodb: pgwas-mongo-0
  ports:
    - name: mongoexternal-svc
      port: 1234
      protocol: TCP
      targetPort: 27017
      nodePort: 32600
#remember to label the pods
