name: deploy-infra

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'helm/**'
      - 'k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder to avoid errors'
#          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Copy files with rsync
        run: rsync -avz ${{ github.workspace }}/ ${{ secrets.USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.HOME_DIR }}/files/dist/infra/
      - name: run script commands via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            kubectl apply -f ${{ secrets.HOME_DIR }}/files/dist/infra/k8s
            helm upgrade ingress ${{ secrets.HOME_DIR }}/files/dist/infra/helm --install --wait --atomic --values=${{ secrets.HOME_DIR }}/files/dist/infra/helm/ingress-values.yaml
            helm upgrade redis-bullmq ${{ secrets.HOME_DIR }}/files/dist/infra/helm --install --wait --values=${{ secrets.HOME_DIR }}/files/dist/infra/helm/redis-values.yaml --set volumes.pvc.name=bullmq
            helm upgrade nats ${{ secrets.HOME_DIR }}/files/dist/infra/helm --install --wait --atomic --values=${{ secrets.HOME_DIR }}/files/dist/infra/helm/nats-values.yaml
      #- run: kubectl apply -f ./k8s
      #- run: helm upgrade ingress ./helm --install --wait --atomic --values=./helm/ingress-values.yaml
      #- run: helm upgrade redis-bullmq ./helm --install --wait --values=./helm/redis-values.yaml --set volumes.pvc.name=bullmq
      #- run: helm upgrade nats ./helm --install --wait --atomic --values=./helm/nats-values.yaml
