name: deploy-static

on:
  push:
    branches:
      - main
    paths:
      - 'servestatic/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd servestatic && docker build -t cubrenig/pgwasservestatic .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push cubrenig/pgwasservestatic
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-1-21-2-do-2-fra-pgwas
      - run: kubectl apply -f ./k8s/servestatic.yaml
      - run: kubectl rollout restart deployment servestatic-deployment
