name: deploy-infra

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'helm/**'
      - 'k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - run: kubectl apply -f ./k8s
      - run: helm upgrade ingress ./helm --install --wait --atomic --values=./helm/ingress-values.yaml
      - run: helm upgrade redis-bullmq ./helm --install --wait --values=./helm/redis-values.yaml --set volumes.pvc.name=bullmq
      - run: helm upgrade nats ./helm --install --wait --atomic --values=./helm/nats-values.yaml
